 MySQL Script generated by MySQL Workbench
-- ter 22 set 2026 08:43:26
-- Wed Sep 23 21:23:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

@@ -8,19 +8,19 @@ SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- Schema banco_insta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- Schema banco_insta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
CREATE SCHEMA IF NOT EXISTS `banco_insta` DEFAULT CHARACTER SET utf8 ;
USE `banco_insta` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- Table `banco_insta`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
CREATE TABLE IF NOT EXISTS `banco_insta`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NULL,
@@ -34,49 +34,49 @@ ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`postagem`
-- Table `banco_insta`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`postagem` (
CREATE TABLE IF NOT EXISTS `banco_insta`.`postagem` (
  `idpostagem` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(140) NOT NULL,
  `data_hora` TIMESTAMP NULL,
  `data_hora` TIMESTAMP NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idpostagem`),
  INDEX `fk_postagem_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    REFERENCES `banco_insta`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curtida`
-- Table `banco_insta`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curtida` (
CREATE TABLE IF NOT EXISTS `banco_insta`.`curtida` (
  `idusuario` INT NOT NULL,
  `idpostagem` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idpostagem`),
  INDEX `fk_usuario_has_postagem_postagem1_idx` (`idpostagem` ASC) VISIBLE,
  INDEX `fk_usuario_has_postagem_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_postagem_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    REFERENCES `banco_insta`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_postagem_postagem1`
    FOREIGN KEY (`idpostagem`)
    REFERENCES `mydb`.`postagem` (`idpostagem`)
    REFERENCES `banco_insta`.`postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- Table `banco_insta`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
CREATE TABLE IF NOT EXISTS `banco_insta`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpostagem` INT NOT NULL,
@@ -86,39 +86,39 @@ CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  INDEX `fk_usuario_has_postagem_usuario2_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_postagem_usuario2`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    REFERENCES `banco_insta`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_postagem_postagem2`
    FOREIGN KEY (`idpostagem`)
    REFERENCES `mydb`.`postagem` (`idpostagem`)
    REFERENCES `banco_insta`.`postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguir`
-- Table `banco_insta`.`seguir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguir` (
CREATE TABLE IF NOT EXISTS `banco_insta`.`seguir` (
  `idseguidor` INT NOT NULL,
  `idseguindo` INT NOT NULL,
  PRIMARY KEY (`idseguidor`, `idseguindo`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`idseguindo` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`idseguidor` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`idseguidor`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    REFERENCES `banco_insta`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`idseguindo`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    REFERENCES `banco_insta`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;